name: 'platform'
version: '1.0.0'
require-dbt-version: [">=1.9.0"]
profile: 'platform'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  platform_database: "{{ env_var('DBT_TARGET_DB', 'ECOMMERCE_DEV') }}"
  raw_database: "{{ env_var('DBT_RAW_DB', 'RAW_DEV') }}"

models:
  platform:
    01_staging:
      +materialized: view
      +schema: rdv_stage
    02_raw_vault:
      +materialized: incremental
      +schema: rdv
      +tags: ['raw_vault']
      +on_schema_change: fail
    03_intermediate:
      +materialized: view
    04_marts:
      core:
        +materialized: view
        +schema: core

seeds:
  platform:
    +schema: hb_dbt_scalefree
    +quote_columns: false
