name: 'platform'
version: '1.0.0'
dbt-cloud:
  project-id: 538624
require-dbt-version: [">=1.9.0"]
profile: 'platform'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  platform_database: "{{ env_var('DBT_TARGET_DB', 'ECOMMERCE_DEV') }}"
  raw_database: "{{ env_var('DBT_RAW_DB', 'RAW_DEV') }}"

models:
  platform:
    01_staging:
      +materialized: view
      +database: BASE__STAGE
      +schema: STAGING
    02_raw_vault:
      +database: BASE__CORE
      +schema: RAW_VAULT
    03_intermediate:
      +materialized: view
      +database: BASE__CORE
      +schema: INTERMEDIATE
    04_marts:
      +materialized: view
      +database: BASE__CORE
      +schema: MARTS
  datavault4dbt_premium_package:
    +database: BASE__AUDIT
    +schema: DV4DBT_PREMIUM_PACKAGE
seeds:
  platform:
    +database: BASE__STAGE
    +schema: SOURCE_DATA__WEBSHOP
    +quote_columns: false
